### ISSUE TITLE
URL失效

### ISSUE THREAD

**Issue by Meteor-Lake** [RW-HPS/RW-HPS#1]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

初始化报错
[2024-11-12 09:34:48] 正在加载事件 [OK]   
[2024-11-12 09:34:48] 正在加载插件命令 [OK]   
[2024-11-12 09:34:48] 正在加载三方图 [OK]   
[2024-11-12 09:34:48] 正在加载网络协议支持 [OK]   
[2024-11-12 09:34:48][Main]: 服务器加载完毕 (2,620 ms)
[2024-11-12 09:34:48][ERROR][OkHttp Dispatcher] [Error] OkHttp Dispatcher: 
java.net.UnknownHostException: jsdelivr.rwhps.net: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java:43)
        at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1211)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1828)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
        at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

### 日志文件

大概是https://jsdelivr.rwhps.net/gh/RW-HPS/RW-HPS-ResFile@1.15_2.0.0_1/无法连接，希望给出新的URL配置

**Comment by deng-rui** [comment]
域名已停止续期, 服务已停止, 当前项目不再提供**任何**维护/支持, 且原团队已解散, 项目删库, github库中存在data/gameData文件夹, 自行移动, 孰不提供教程
**我认为这是门槛的一部分** 我不想再提供无脑傻逼方案
