### ISSUE TITLE
玩家使用空名称进入服务器导致 NPE

### ISSUE THREAD

**Issue by byzp** [RW-HPS/RW-HPS#159]
ubuntu server 21.10 arm, openjdk-17-jdk-headless,  5.2.0
ubuntu@ubuntu:~/rw$ java -jar *.jar
----------------------------------------------------
_______          __           _    _ _____   _____
|  __ \ \        / /          | |  | |  __ \ / ____|
| |__) \ \  /\  / /   ______  | |__| | |__) | (___
|  _  / \ \/  \/ /   |______| |  __  |  ___/ \___ \
| | \ \  \  /\  /             | |  | | |     ____) |
|_|  \_\  \/  \/              |_|  |_|_|    |_____/
----------------------------------------------------
[2022-02-26 04:31:56 UTC] Load ing...
[2022-02-26 04:31:56 UTC] 服务器当前检测到的语言是: 中文[已使用]
[2022-02-26 04:31:56 UTC] 您好! 欢迎您使用RW-HPS
[2022-02-26 04:31:56 UTC] 本项目Github地址: https://github.com/RW-HPS/RW-HPS
[2022-02-26 04:31:57 UTC] 正在加载命令...
[2022-02-26 04:31:57 UTC] 正在加载事件...
[2022-02-26 04:31:57 UTC] Load OK 1.14 Protocol
[2022-02-26 04:31:57 UTC] 服务器加载完毕
[2022-02-26 04:31:57 UTC] 服务器已加载 1 个插件
[2022-02-26 04:31:57 UTC] 正在加载三方图...
[2022-02-26 04:31:57 UTC] Server Run PID : 5713
[2022-02-26 04:31:58 UTC] 正在开启服务器...
[2022-02-26 04:31:58 UTC] 正在启动端口监听...
[2022-02-26 04:31:58 UTC] 服务器启动完毕
[2022-02-26 04:32:06 UTC] [***]: -qc -map 'Crossing Large (10p)'
Exception in thread "PluginEventASync-1" java.lang.NullPointerException
        at com.github.dr.rwserver.data.player.Player.sendSystemMessage(Player.kt:83)
        at com.github.dr.rwserver.core.Call.sendSystemMessage$lambda-6(Call.kt:71)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.core.Call.sendSystemMessage(Call.kt:71)
        at com.github.dr.rwserver.game.Event.registerPlayerLeaveEvent(Event.kt:87)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10$lambda-9(PluginEventManage.kt:74)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10(PluginEventManage.kt:73)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "PluginEventASync-3" java.lang.NullPointerException
        at com.github.dr.rwserver.data.player.Player.sendSystemMessage(Player.kt:83)
        at com.github.dr.rwserver.core.Call.sendSystemMessage$lambda-6(Call.kt:71)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.core.Call.sendSystemMessage(Call.kt:71)
        at com.github.dr.rwserver.game.Event.registerPlayerLeaveEvent(Event.kt:87)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10$lambda-9(PluginEventManage.kt:74)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10(PluginEventManage.kt:73)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "PluginEventASync-5" java.lang.NullPointerException
        at com.github.dr.rwserver.core.Call.upDataGameData$lambda-9(Call.kt:96)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.core.Call.upDataGameData(Call.kt:94)
        at com.github.dr.rwserver.game.Event.registerPlayerLeaveEvent(Event.kt:72)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10$lambda-9(PluginEventManage.kt:74)
        at com.github.dr.rwserver.struct.Seq.each(Seq.java:173)
        at com.github.dr.rwserver.data.plugin.PluginEventManage$Companion.registerEventAll$lambda-11$lambda-10(PluginEventManage.kt:73)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by deng-rui** [comment]
看起来是由于玩家名为空导致

将加入一个最短名称检测来抑制此错误
