### ISSUE TITLE
[ARM-Linux] Connection display EOF 

### ISSUE THREAD

**Issue by deng-rui** [RW-HPS/RW-HPS#368]
**Describe the bug**
Headless end join prompt EOF

**To Reproduce**
Use ARM Linux Start RW-HPS

**Expected behavior**
[2023-01-21 20:29:45] Run GameHeadless ID: GameModularLoadClass@b86de0d
[2023-01-21 20:29:46] Player: RW-HPS Core Headless Join Server
RW-HPS Core Headless Join Server

**Screenshots**

*Pplease complete the following information:**
 - Device: [e.g. iPhone6] Linux armv7l
 - OS: [e.g. iOS8.1] Ubuntu
 - Game Version [e.g. 1.14] 1.15
 - Server Version [e.g.1.4.0.6] ALL

**Additional context**
```
[2023-01-21 21:25:38] Run GameHeadless ID: GameModularLoadClass@1cd8c7a
[GameModularLoadClass@1cd8c7a]  :  id:2: network:ReceiveWorker: EOF reading packet
[GameModularLoadClass@1cd8c7a]  :  java.io.EOFException
[GameModularLoadClass@1cd8c7a]  :  cause:null
[Main.kt] : invoke : 207
[2023-01-21 21:25:43] DEBUG: 
java.io.EOFException
[Main.kt] : invoke : 207
[2023-01-21 21:25:43] DEBUG: 
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
[Main.kt] : invoke : 207
[2023-01-21 21:25:43] DEBUG: 
	at com.corrodinggames.rts.gameFramework.j.d.a(SourceFile:735)
[Main.kt] : invoke : 207
[2023-01-21 21:25:43] DEBUG: 
	at com.corrodinggames.rts.gameFramework.j.d.run(SourceFile:683)
[Main.kt] : invoke : 207
[2023-01-21 21:25:43] DEBUG: 
	at java.base/java.lang.Thread.run(Unknown Source)
[GameModularLoadClass@1cd8c7a]  :  id:2: handleRemoteDisconnect
[GameModularLoadClass@1cd8c7a]  :  reportProblem:The server disconnected  (Time out)
[GameModularLoadClass@1cd8c7a]  :  id:2: handleRemoteDisconnect: connection is already disconnecting
```
```
root@localhost:/sdcard/Ma#  uname -a
Linux localhost 3.10.0_s40 #1 SMP Mon May 23 12:23:40 CST 2016 armv7l armv7l armv7l GNU/Linux
root@localhost:/sdcard/Ma#  uname -m
armv7l
```

**Comment by deng-rui** [comment]
Maybe it's a bug under ARM? I don't know
