### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by nyakochanNeee** [RW-HPS/RW-HPS#375]
**Describe the bug**
无法加入服务器(非官方地图) 看到是这个就来提交issue了
cant join the server and see chat says RWHPS so I come to put an issue here

**To Reproduce**
1. 多人游戏
2. 选择一个服务器 1.15-RN (非官方地图 需要传输下载的地图)
3. 加入服务器
4. 开始游戏时提示  Receiving network data: 4072/4088884 和 链接超时的断开链接

**Screenshots**
![image](https://user-images.githubusercontent.com/100355329/215110053-c2f2ea91-a762-4888-828c-0e60e6121a58.png)

**lastrunlog**
2023-01-27 21:28:19.583: Receiving network data: 4072/4088884
2023-01-27 21:28:19.638: Receiving network data: 4072/4088884
2023-01-27 21:28:19.650: Receiving network data: 4072/4088884
2023-01-27 21:28:19.665: Receiving network data: 4072/4088884
2023-01-27 21:28:19.680: Receiving network data: 4072/4088884
2023-01-27 21:28:19.695: Receiving network data: 4072/4088884
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:324)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:919)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:149)
	at com.corrodinggames.rts.gameFramework.j.d.a(SourceFile:783)
	at com.corrodinggames.rts.gameFramework.j.d.run(SourceFile:683)
	at java.base/java.lang.Thread.run(Thread.java:830)
2023-01-27 21:28:19.701: id:1: network:ReceiveWorker: Connection reset
2023-01-27 21:28:19.701: id:1: handleRemoteDisconnect
2023-01-27 21:28:19.701: reportProblem:The server disconnected  (Time out)
2023-01-27 21:28:19.702: id:1: handleRemoteDisconnect: connection is already disconnecting

*Pplease complete the following information:**
 - OS: [windows 10]
 - Game Version [1.15]
 - Server Version [1.1.0-DEV4] see this in https://api.data.der.kim/RCN/Info

**Additional context**
在手机上是正常的 但是电脑上就无法正常下载(地图)

**Comment by nyakochanNeee** [comment]
可能这个issues有点和 same rwmod same server smartphone can join PC HOST ， PC can't join phone #372 这个冲突了 差不多的问题 但是我还是想要提交这个issues ( 因为我的是地图 他的是mod (确信)

**Comment by deng-rui** [comment]
这个问题我也不太清楚

因此 RELAY-CN项目考虑升级架构 V1->V2

**Comment by deng-rui** [comment]
解决
