### ISSUE TITLE
代码在idea中启动失败问题

### ISSUE THREAD

**Issue by x-xiao98** [RW-HPS/RW-HPS#407]
我下载了rw-hps源码后，在idea中启动main，报错
[2023-05-22 11:06:43] 服务器当前检测到的语言是: 中文[已使用]
[2023-05-22 11:06:43] 您好! 欢迎您使用RW-HPS
[2023-05-22 11:06:43] 本项目Github地址: https://github.com/RW-HPS/RW-HPS
[2023-05-22 11:06:43] 感谢 AnsdoShip Studio 与 Rukkit Dev 对本项目的帮助
[Thread.java] : dispatchUncaughtException : 2001
[2023-05-22 11:06:43] [Error] Main: 
net.rwhps.server.util.log.exp.VariableException: [Angent Init Error] Please check the JDK version, Use Java11 or Java11+
	at net.rwhps.server.dependent.AgentAttachData$Companion.getInstPrivate(AgentAttachData.kt:28)
	at net.rwhps.server.dependent.AgentAttachData$Companion.access$getInstPrivate(AgentAttachData.kt:23)
	at net.rwhps.server.dependent.AgentAttachData.<init>(AgentAttachData.kt:20)
	at net.rwhps.server.dependent.HeadlessProxyClass.<init>(HeadlessProxyClass.kt:40)
	at net.rwhps.server.Main.main(Main.kt:126)

jdk版本没有问题，推测是agent代理方面的事情。我不太熟悉agent这里。想问下这种情况应该如何解决？

**Comment by deng-rui** [comment]
这个问题是ideadebug的参数问题，和agentmain设置有关，但是我也不知道～

**Comment by deng-rui** [comment]
![Uploading image.png…]()

**Comment by deng-rui** [comment]
![image](https://github.com/RW-HPS/RW-HPS/assets/39623218/baf9890b-0b2f-4f73-b212-493f246bae9a)

**Comment by deng-rui** [comment]
![image](https://github.com/RW-HPS/RW-HPS/assets/39623218/7b9ac8eb-d8af-4903-ba6d-21171537cc1a)

请自行手动添加Debug配置

**Comment by deng-rui** [comment]
![image](https://github.com/RW-HPS/RW-HPS/assets/39623218/26a0492c-73d2-4de2-b0f1-14a234b23b37)
