### ISSUE TITLE
在windows平台下的Docker中运行hps出现无法读取字体数据问题

### ISSUE THREAD

**Issue by allureluoli** [RW-HPS/RW-HPS#574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

经测试在windows和linux平台下都没有这个报错，但在docker容器中出现了这个报错。
在报错后使用uplist add 命令将得不到任何反馈。
输入log命令返回报错2的内容。
dockefile内容如下：
其一
FROM vt167098/openjdk21_jre

WORKDIR /app

COPY Server-All.jar /app/Server-All.jar

CMD ["java", "-jar", "Server-All.jar"]
其二
FROM vt167098/openjdk21_jre

WORKDIR /app

COPY Server.jar /app/Server.jar

COPY data /app/data

CMD ["java", "-jar", "Server.jar"]
无论是第一种还是第二种都可以复现错误。

### 日志文件

# 报错1
[2024-04-25 19:14:18] [Error] Thread-9:
java.lang.RuntimeException: java.io.IOException: Problem reading font data.
        at com.corrodinggames.rts.java.e.a(SourceFile:585)
        at com.corrodinggames.rts.java.e.a(SourceFile:413)
        at com.corrodinggames.rts.java.e.a(SourceFile:1445)
        at com.corrodinggames.rts.java.e.a(SourceFile:3741)
        at com.corrodinggames.rts.gameFramework.l.Y(SourceFile:1432)
        at com.corrodinggames.rts.game.i.a(SourceFile:777)
        at com.corrodinggames.rts.gameFramework.l.a(SourceFile:597)
        at com.corrodinggames.rts.java.Main.h(SourceFile:1380)
        at com.corrodinggames.rts.java.u.c(SourceFile:302)
        at com.corrodinggames.rts.java.u.b(SourceFile:286)
        at com.corrodinggames.rts.java.u.render(SourceFile:1382)
        at com.corrodinggames.rts.java.b.updateAndRender(SourceFile:255)
        at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
        at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
        at com.corrodinggames.rts.java.j.run(SourceFile:1464)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source)
        at java.desktop/java.awt.Font.createFont(Unknown Source)
        at com.corrodinggames.rts.java.e.a(SourceFile:563)
        ... 15 more
# 报错2
[2024-04-25 19:18:21] [Error] Core-1:
java.lang.ClassFormatError: Truncated class file
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at net.rwhps.server.dependent.hot.DynamicByteClassLoader.findClass(DynamicByteClassLoader.kt:23)
        at net.rwhps.server.dependent.hot.DynamicByteClassLoader.findClass(DynamicByteClassLoader.kt:18)
        at net.rwhps.server.dependent.HotLoadClass.load(HotLoadClass.kt:24)
        at net.rwhps.server.command.CoreCommands._init_$lambda$22(CoreCommands.kt:283)
        at net.rwhps.server.util.game.command.CommandHandler.handleMessage(CommandHandler.java:96)
        at net.rwhps.server.Main.inputMonitor(Main.kt:238)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

### 截图

![cad07c13d035c0cc8dc6193fbc5e01d6](https://github.com/RW-HPS/RW-HPS/assets/106828088/46457b9c-1c99-437e-8603-c158128ae56d)

### 还有别的吗？

使用的jdk是: vt167098/openjdk21_jre
系统windows 11
总内存大小32g
cpu e5-2689v4

**Comment by deng-rui** [comment]
报错2 不应该被发生, 你应该是调用了某个测试命令, 这个命令是测试热加载/热替换Class (热更新)的来着

**Comment by deng-rui** [comment]
字体加载错误是不是没link data文件夹? 你看看服务器目录的 data/gameData有没有font.7z?

**Comment by allureluoli** [comment]
我确认了一下，容器下目录是存在正确路径的Game-Fonts.7z的，且报错依然发生[附图]
![图片](https://github.com/RW-HPS/RW-HPS/assets/106828088/cefb2e9d-ac8e-4a7c-be67-a95ba8b6b95e)
![图片](https://github.com/RW-HPS/RW-HPS/assets/106828088/e60f52fb-cf16-4782-9232-bd147c9e1820)

**Comment by deng-rui** [comment]
我查了一下这个问题, 好像是Java AWT的Font加载需要使用java.io.tmpdir (临时文件), docker不能访问临时文件夹? (不太清楚哎, 没遇到, 我这边没windows-Docker环境)

**Comment by allureluoli** [comment]
我找到了解决问题的方法
我使用 FROM azul/zulu-openjdk-debian:21-jre-latest
替换掉了  FROM vt167098/openjdk21_jre
这样做会非常完美的运行HPS，没有任何问题。
后一个 jre使用的是 Alpine Linux 明显的更为轻量级，要少200MB，但无法使用比较可惜。
### 经过我的测试发现了一些线索：
在dev11版本的RW-HPS使用vt167098/openjdk21_jre，并不会出现这个错误。而M5版本则会出现，也就是说这个错误是M5版本更新后出现的。
而在Linux环境下，M5版本的HPS如果使用vt167098/openjdk21_jre，会增加一个新的报错
'''bash

[2024-04-26 00:25:20] server.load.plugin:
kotlin.UninitializedPropertyAccessException: lateinit property hps has not been initialized
        at net.rwhps.server.game.manage.HeadlessModuleManage.getHps(HeadlessModuleManage.kt:23)
        at net.rwhps.server.plugin.beta.UpListMain.<init>(UpListMain.kt:187)
        at net.rwhps.server.custom.LoadCoreCustomPlugin.<init>(LoadCoreCustomPlugin.kt:38)
        at net.rwhps.server.Main$main$2.invoke(Main.kt:139)
        at net.rwhps.server.Main$main$2.invoke(Main.kt:137)
        at net.rwhps.server.util.log.LoadLogUtils.loadStatusLog(LoadLogUtils.kt:33)
        at net.rwhps.server.Main.main(Main.kt:137)

'''

**Comment by deng-rui** [comment]
dev11不出现其实是因为渲染被我干死了（，你可以尝试把服务端版本往前再试试，M4/M3，应该也会有字体错误

**Comment by deng-rui** [comment]
另，我开发使用zulu jdk，好像openjdk有奇奇怪怪的问题，你可以找一个 zulu jre的doxker image试试？

**Comment by deng-rui** [comment]
超时, 有需要再重新启用
